/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Datos.EstadoCivilDAO;
import Datos.OcupacionDAO;
import Entidades.Abogado;
import Entidades.CategoriaAbogado;
import negocio.ClienteControl;
import Entidades.Cliente;
import Entidades.EstadoCivil;
import Entidades.Ocupacion;
import negocio.AbogadoControl;
import negocio.CategoriaAbogadoControl;
import negocio.EstadoCivilControl;
import negocio.TestigoControl;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.TestigoControl;

/**
 *
 * @author ANGEL-GARCIA
 */
public class FrmCliente extends javax.swing.JInternalFrame {

    private final EstadoCivilControl estadoCivilControl;
    private final ClienteControl clienteControl;
    private final TestigoControl testigoControl;
    private boolean estadoEditando;
    private Cliente clienteAux;
    private int seleccionCliente;

    public FrmCliente() {
        initComponents();
        buttonGroup1.add(btnActivo);
        buttonGroup1.add(btnInactivo);
        clienteControl = new ClienteControl();
        estadoCivilControl = new EstadoCivilControl();
        testigoControl = new TestigoControl();
        jTabbedPane1.setEnabledAt(1, false);
        DefaultTableModel model;

        tblClient.setModel(clienteControl.listar());
        llenarCombobox();
        seleccionCliente = -1;
        estadoEditando = false;
        clienteAux = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        tblClientes = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDomicilio = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtFecha = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jdbEstadoCivil = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        btnActivo = new javax.swing.JRadioButton();
        btnInactivo = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jdbOcupacion = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setRequestFocusEnabled(false);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0), 3));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Nombre:");

        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtBuscar.setPreferredSize(new java.awt.Dimension(2, 25));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Buscar.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnVer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/siguiente-boton.png"))); // NOI18N
        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Actualizar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        tblClientes.setViewportView(tblClient);

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Clientes");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tblClientes)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18))))
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer)
                    .addComponent(btnNuevo)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43)
                .addComponent(tblClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtBuscar.getAccessibleContext().setAccessibleName("txtBuscar");
        btnVer.getAccessibleContext().setAccessibleName("btnVer");
        btnNuevo.getAccessibleContext().setAccessibleName("btnNuevo");
        btnEditar.getAccessibleContext().setAccessibleName("btnEditar");

        jTabbedPane1.addTab("Listado", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel17.setText("Nombres :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel18.setText("Apellidos :");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel21.setText("Correo :");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel22.setText("Domicilio :");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtNombre.setPreferredSize(new java.awt.Dimension(2, 25));

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtApellido.setPreferredSize(new java.awt.Dimension(2, 25));

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtCorreo.setPreferredSize(new java.awt.Dimension(2, 25));

        txtDomicilio.setColumns(5);
        txtDomicilio.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtDomicilio.setRows(3);
        txtDomicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        jScrollPane4.setViewportView(txtDomicilio);
        txtDomicilio.setLineWrap(true);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel19.setText("Identidad :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel20.setText("Teléfono :");

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel23.setText("Fecha/nacimiento :");

        txtIdentidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtIdentidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtIdentidad.setMinimumSize(new java.awt.Dimension(2, 22));
        txtIdentidad.setPreferredSize(new java.awt.Dimension(2, 25));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtTelefono.setMinimumSize(new java.awt.Dimension(2, 22));
        txtTelefono.setPreferredSize(new java.awt.Dimension(2, 25));

        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtFecha.setDateFormatString("dd-MM-yyyy");
        txtFecha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFecha.setPreferredSize(new java.awt.Dimension(89, 25));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel25.setText("Estado civil :");

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Estado:");

        jdbEstadoCivil.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jdbEstadoCivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        jdbEstadoCivil.setPreferredSize(new java.awt.Dimension(28, 25));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel27.setText("Ocupación:");

        btnActivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnActivo.setSelected(true);
        btnActivo.setText("Activo");
        btnActivo.setActionCommand("");
        btnActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivoActionPerformed(evt);
            }
        });

        btnInactivo.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnInactivo.setText("Inactivo");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jdbOcupacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jdbOcupacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        jdbOcupacion.setPreferredSize(new java.awt.Dimension(28, 25));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Clientes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 764, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel26)
                        .addGap(41, 41, 41)
                        .addComponent(btnActivo)
                        .addGap(50, 50, 50)
                        .addComponent(btnInactivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel22)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel21)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23)
                                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbOcupacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jdbEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jdbOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(btnActivo)
                            .addComponent(btnInactivo))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnCancelar)))
                .addGap(95, 95, 95)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 756, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Mantenimiento", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Mantenimiento");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        irClientes();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (estadoEditando) {

            try {
                if (permitirGuardar()) {
                    editar();
                    tblClient.setModel(clienteControl.listar());

                    irClientes();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage(), null, JOptionPane.WARNING_MESSAGE);
            }

        } else {

            try {
                if (permitirGuardar()) {
                    guardar();
                    tblClient.setModel(clienteControl.listar());

                    irClientes();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e.getMessage() + "escritorio", null, JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    public void editar() {

        int estadoCivil = 0;

        for (EstadoCivil e : new EstadoCivilDAO().listarGeneral()) {
            if (e.getNombre().equals(jdbEstadoCivil.getSelectedItem() + "")) {
                estadoCivil = e.getId();
            }
        }

        int estado = 0;

        if (btnActivo.isSelected()) {
            estado = 1;
        } else {
            estado = 0;
        }

        int ocupacion = 0;

        for (Ocupacion e : new OcupacionDAO().listar("")) {
            if (e.getNombre().equals(jdbOcupacion.getSelectedItem() + "")) {
                ocupacion = e.getId();
            }
        }

        java.util.Date d = txtFecha.getDate();

        java.sql.Date date2 = new java.sql.Date(d.getTime());

        System.out.println(clienteControl.editar(clienteAux.getIdCliente(), txtNombre.getText(), txtApellido.getText(), txtIdentidad.getText(),
                txtTelefono.getText(), txtCorreo.getText(), txtDomicilio.getText(), date2, estadoCivil, ocupacion, estado));

        clienteAux = null;
        // JOptionPane.showMessageDialog(rootPane, "Registro Guardado Correctamente",null,JOptionPane.WARNING_MESSAGE);

    }

    public void guardar() {

        int estadoCivil = 0;

        for (EstadoCivil e : new EstadoCivilDAO().listarGeneral()) {
            if (e.getNombre().equals(jdbEstadoCivil.getSelectedItem() + "")) {
                estadoCivil = e.getId();
            }
        }

        int estado = 0;

        if (btnActivo.isSelected()) {
            estado = 1;
        } else {
            estado = 0;
        }

        int ocupacion = 0;

        for (Ocupacion e : new OcupacionDAO().listar("")) {
            if (e.getNombre().equals(jdbOcupacion.getSelectedItem() + "")) {
                ocupacion = e.getId();
            }
        }

        java.util.Date d = txtFecha.getDate();

        java.sql.Date date2 = new java.sql.Date(d.getTime());

        System.out.println(clienteControl.insertar(txtNombre.getText(), txtApellido.getText(), txtIdentidad.getText(),
                txtTelefono.getText(), txtCorreo.getText(), txtDomicilio.getText(), date2, estadoCivil, ocupacion, estado));

        // JOptionPane.showMessageDialog(rootPane, "Registro Guardado Correctamente");

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivoActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        int seleccion = tblClient.rowAtPoint(evt.getPoint());

        if (seleccion > -1) {
            seleccionCliente = Integer.parseInt(tblClient.getValueAt(seleccion, 0) + "");
            //System.out.println(seleccionAbogado);
        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (seleccionCliente > -1) {
            ponerDatos(seleccionCliente);
            irAEditar();

            seleccionCliente = -1;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro del cliente", null, JOptionPane.WARNING_MESSAGE);
            seleccionCliente = -1;
        }
        tblClient.clearSelection();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        irNuevo();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if (seleccionCliente > -1) {
            ponerDatos(seleccionCliente);
            irVer();

            seleccionCliente = -1;
        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de Cliente", null, JOptionPane.WARNING_MESSAGE);
            seleccionCliente = -1;
        }
        tblClient.clearSelection();
    }//GEN-LAST:event_btnVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtBuscar.getText().length() != 0) {
            tblClient.setModel(clienteControl.listarNombre(txtBuscar.getText()));
        } else {
            tblClient.setModel(clienteControl.listar());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public boolean permitirGuardar() {

        if (txtNombre.getText().length() == 0 || txtNombre.getText().length() > 30) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombre debe estar lleno, con limite de 30 caracteres", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (contieneNumero(txtNombre.getText())) {
            JOptionPane.showMessageDialog(rootPane, "El campo nombre no debe tener numeros", null, JOptionPane.WARNING_MESSAGE);

            return false;
        }

        if (txtApellido.getText().length() == 0 || txtApellido.getText().length() > 30) {
            JOptionPane.showMessageDialog(rootPane, "El campo apellido debe estar lleno, con limite de 30 caracteres", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (contieneNumero(txtApellido.getText())) {
            JOptionPane.showMessageDialog(rootPane, "El campo apellido no debe tener numeros", null, JOptionPane.WARNING_MESSAGE);

            return false;
        }

        if (txtIdentidad.getText().length() == 0 || txtIdentidad.getText().length() > 17) {
            JOptionPane.showMessageDialog(rootPane, "El campo identidad debe estar lleno, con limite de 17 caracteres", null, JOptionPane.WARNING_MESSAGE);

            return false;
        }

        if (contieneLetra(txtIdentidad.getText())) {
            JOptionPane.showMessageDialog(rootPane, "El campo identidad no debe tener letras");

            return false;
        }

        if (txtTelefono.getText().length() == 0 || txtTelefono.getText().length() > 17) {
            JOptionPane.showMessageDialog(rootPane, "El campo telefono debe estar lleno, con limite de 17 caracteres", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (contieneLetra(txtTelefono.getText())) {
            JOptionPane.showMessageDialog(rootPane, "El campo telefono no debe tener letras", null, JOptionPane.WARNING_MESSAGE);

            return false;
        }

        if (txtCorreo.getText().length() == 0 || txtCorreo.getText().length() > 100) {
            JOptionPane.showMessageDialog(rootPane, "El campo telefono debe estar lleno, con limite de 100 caracteres", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        if (txtDomicilio.getText().length() == 0 || txtDomicilio.getText().length() > 250) {
            JOptionPane.showMessageDialog(rootPane, "El campo dimicilio debe estar lleno, con limite de 100 caracteres", null, JOptionPane.WARNING_MESSAGE);
            return false;
        }

        Calendar fechaSeleccionada = txtFecha.getCalendar();
        Calendar fechaSistema = Calendar.getInstance();
        int anio = fechaSistema.get(Calendar.YEAR) - fechaSeleccionada.get(Calendar.YEAR);

        if (txtFecha.getDate() == null || anio < 18) {
            JOptionPane.showMessageDialog(rootPane, "Fecha invalida:" + (anio), null, JOptionPane.WARNING_MESSAGE);
            return false;
        }
        return true;
    }

    public boolean contieneLetra(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (Character.isLetter(s.charAt(i))) {
                return true;
            }
        }

        return false;
    }

    public boolean contieneNumero(String s) {
        for (int i = 0; i < s.length(); i++) {
            if (Character.isDigit(s.charAt(i))) {
                return true;
            }
        }

        return false;
    }

    public void irAEditar() {
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);
        estadoEditando = true;
    }

    public void irNuevo() {
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);

        estadoEditando = false;
    }

    public void irVer() {
        jTabbedPane1.setSelectedIndex(1);
        jTabbedPane1.setEnabledAt(1, true);
        jTabbedPane1.setEnabledAt(0, false);

        btnGuardar.setEnabled(false);
        btnActivo.setEnabled(false);
        btnInactivo.setEnabled(false);

        estadoEditando = false;
    }

    public void limpiarComponentes() {

        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtDomicilio.setText("");
        txtIdentidad.setText("");
        txtTelefono.setText("");
        txtFecha.setCalendar(null);

        btnActivo.setSelected(true);
    }

    public void irClientes() {
        limpiarComponentes();

        jTabbedPane1.setSelectedIndex(0);
        jTabbedPane1.setEnabledAt(1, false);
        jTabbedPane1.setEnabledAt(0, true);

        btnGuardar.setEnabled(true);
        btnActivo.setEnabled(true);
        btnInactivo.setEnabled(true);

        estadoEditando = false;

        clienteAux = null;
    }

    public void ponerDatos(int id) {
        clienteAux = clienteControl.listandoUnRegistro(id);

        System.out.println("asdfsdfsdfsd" + clienteAux.getIdCliente());
        txtNombre.setText(clienteAux.getNombre());
        txtApellido.setText(clienteAux.getApellidos());
        txtCorreo.setText(clienteAux.getCorreo());
        txtDomicilio.setText(clienteAux.getDomicilio());
        txtIdentidad.setText(clienteAux.getNum_identidad());
        txtTelefono.setText(clienteAux.getNum_telefono());
        txtFecha.setDate(clienteAux.getFechaNacimiento());

        if (clienteAux.getEstado() == 1) {
            btnActivo.setSelected(true);
        } else {
            btnInactivo.setSelected(true);
        }

        for (EstadoCivil ec : new EstadoCivilDAO().listarGeneral()) {
            System.out.println(ec.getNombre());
            if (ec.getId() == clienteAux.getEstadoCivil()) {
                // String s = ec.getNombre();
                jdbEstadoCivil.setSelectedItem(ec.getNombre() + "");
                break;
            }
        }

        for (Ocupacion ec : new OcupacionDAO().listar("")) {
            System.out.println(ec.getNombre());
            if (ec.getId() == clienteAux.getOcupacion()) {
                jdbOcupacion.setSelectedItem(ec.getNombre());
                break;
            }
        }

    }

    private void llenarCombobox() {

        // DefaultComboBoxModel item2 = this.testigoControl.ComboboxOcupacion();
        //jdbOcupacion.setModel(item2);
        //DefaultComboBoxModel item3 = this.testigoControl.ComboboxEstadoCivil();
        //jdbEstadoCivil.setModel(item3);
        for (EstadoCivil ec : new EstadoCivilDAO().listarGeneral()) {
            jdbEstadoCivil.addItem(ec.getNombre());
        }

        for (Ocupacion ec : new OcupacionDAO().listar("")) {
           jdbOcupacion.addItem(ec.getNombre());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnActivo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JRadioButton btnInactivo;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jdbEstadoCivil;
    private javax.swing.JComboBox<String> jdbOcupacion;
    private javax.swing.JTable tblClient;
    private javax.swing.JScrollPane tblClientes;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDomicilio;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
