/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableRowSorter;
import negocio.TestigoControl;
import Entidades.EstadoCivil;
import Entidades.Ocupacion;
import Entidades.Testigo;
import Entidades.TipoTestigo;
import javax.swing.ImageIcon;
import negocio.EvidenciaControl;

/**
 *
 * @author Buddys
 */
public class FrmTestigoo extends javax.swing.JInternalFrame {

    private final TestigoControl CONTROL;
    private String accion;
    private Testigo objeto;
    private static final String EMAIL_PATTERN
            = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
            + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";

    /**
     * Creates new form FrmTestigoo
     */
    public FrmTestigoo() {
        initComponents();
        this.CONTROL = new TestigoControl();
        this.objeto = new Testigo();
        this.listar("");
        this.llenarCombobox();
        panelGeneral.setEnabledAt(1, false);
        txtId.setVisible(false);

    }

    private void listar(String parametro) {
        tablaListado.setModel(this.CONTROL.listar(parametro));
        TableRowSorter control = new TableRowSorter(tablaListado.getModel());
        tablaListado.setRowSorter(control);
        this.ocultarColumnas();
        //lblTotalMostrados.setText("Mostrando "+this.CONTROL.totalMostrados()+" registros"+" de "+this.CONTROL.totalMostrados());
    }

    private void llenarTextField(int id) {
        EvidenciaControl evidencia = new EvidenciaControl();
        String respuesta = evidencia.buscar(id);
        this.lblTitulocaso.setText("Titulo Caso: " + respuesta);
    }

    private void limpiar() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtIdentidad.setText("");
        txtTelefono.setText("");
        txtCorreo.setText("");
        txtDomicilio.setText("");
        txtFecha.setDate(null);
        txtIdCaso.setText("");
        lblTitulocaso.setText("");
    }

    private void llenarCombobox() {
        DefaultComboBoxModel item1 = this.CONTROL.llenandoComboTipoTestigo();
        cboTestigo.setModel(item1);
        DefaultComboBoxModel item2 = this.CONTROL.ComboboxOcupacion();
        cboOcupacion.setModel(item2);
        DefaultComboBoxModel item3 = this.CONTROL.ComboboxEstadoCivil();
        cboEstadoCivil.setModel(item3);
    }

    private void mensajeError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Sistema", JOptionPane.ERROR_MESSAGE);
    }

    private void mensajeOk(String mensaje) {
        JOptionPane.showMessageDialog(this,mensaje,"Sistema", JOptionPane.PLAIN_MESSAGE,new ImageIcon("src\\imagenes\\confirmar.png"));
    }

    private void ocultarColumnas() {
        tablaListado.getColumnModel().getColumn(15).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(15).setMinWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(15).setMaxWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(15).setMinWidth(0);
        //
        tablaListado.getColumnModel().getColumn(14).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(14).setMinWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(14).setMaxWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(14).setMinWidth(0);
        //
        tablaListado.getColumnModel().getColumn(13).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(13).setMinWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(13).setMaxWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(13).setMinWidth(0);
        //
        tablaListado.getColumnModel().getColumn(6).setMaxWidth(0);
        tablaListado.getColumnModel().getColumn(6).setMinWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(6).setMaxWidth(0);
        tablaListado.getTableHeader().getColumnModel().getColumn(6).setMinWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGeneral = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        btnDesactivar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cboEstadoCivil = new javax.swing.JComboBox<>();
        txtTelefono = new javax.swing.JTextField();
        txtIdentidad = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        cboTestigo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDomicilio = new javax.swing.JTextArea();
        txtFecha = new com.toedter.calendar.JDateChooser();
        txtCorreo = new javax.swing.JTextField();
        cboOcupacion = new javax.swing.JComboBox<>();
        btnLimpiar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtIdCaso = new javax.swing.JTextField();
        btnBuscarIdcaso = new javax.swing.JButton();
        lblTitulocaso = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        panelGeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0), 3));
        panelGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0), 3));

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaListado);

        txtBuscar.setText(" ");
        txtBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtBuscar.setMinimumSize(new java.awt.Dimension(3, 22));
        txtBuscar.setPreferredSize(new java.awt.Dimension(6, 22));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre Testigo");

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar (1).png"))); // NOI18N
        btnBuscar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/documento.png"))); // NOI18N
        btnEditar.setText("Actualizar");
        btnEditar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setPreferredSize(new java.awt.Dimension(103, 32));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnActivar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/activacion.png"))); // NOI18N
        btnActivar.setText("Activar");
        btnActivar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        btnDesactivar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDesactivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hibernacion.png"))); // NOI18N
        btnDesactivar.setText("Desactivar");
        btnDesactivar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesactivarActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Testigo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelGeneral.addTab("Listado", jPanel2);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0), 3));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Testigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tipo Testigo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Apellido");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Identidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Teléfono");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Estado Civil");

        cboEstadoCivil.setBorder(null);
        cboEstadoCivil.setPreferredSize(new java.awt.Dimension(28, 27));

        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtTelefono.setMinimumSize(new java.awt.Dimension(28, 20));
        txtTelefono.setPreferredSize(new java.awt.Dimension(28, 27));

        txtIdentidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtIdentidad.setMinimumSize(new java.awt.Dimension(28, 20));
        txtIdentidad.setPreferredSize(new java.awt.Dimension(28, 27));

        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtApellido.setMinimumSize(new java.awt.Dimension(28, 20));
        txtApellido.setPreferredSize(new java.awt.Dimension(28, 27));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtNombre.setMinimumSize(new java.awt.Dimension(28, 20));
        txtNombre.setPreferredSize(new java.awt.Dimension(28, 27));

        txtId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));

        cboTestigo.setBorder(null);
        cboTestigo.setPreferredSize(new java.awt.Dimension(28, 27));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Ocupación");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Correo");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Fecha Nacimiento");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Domicilio");

        txtDomicilio.setColumns(20);
        txtDomicilio.setRows(5);
        txtDomicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        jScrollPane2.setViewportView(txtDomicilio);
        txtDomicilio.setLineWrap(true);

        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtFecha.setDateFormatString("yyyy-MM-dd");
        txtFecha.setPreferredSize(new java.awt.Dimension(28, 27));

        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtCorreo.setPreferredSize(new java.awt.Dimension(28, 27));

        cboOcupacion.setBorder(null);
        cboOcupacion.setPreferredSize(new java.awt.Dimension(28, 27));

        btnLimpiar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/escoba.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar (1).png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setPreferredSize(new java.awt.Dimension(103, 32));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("ID Caso");

        txtIdCaso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(170, 122, 0)));
        txtIdCaso.setMinimumSize(new java.awt.Dimension(28, 20));
        txtIdCaso.setPreferredSize(new java.awt.Dimension(28, 27));

        btnBuscarIdcaso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarIdcaso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar (1).png"))); // NOI18N
        btnBuscarIdcaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdcasoActionPerformed(evt);
            }
        });

        lblTitulocaso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitulocaso.setText("Titulo Caso:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(259, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(2, 2, 2)))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboEstadoCivil, 0, 215, Short.MAX_VALUE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtIdentidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboTestigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addComponent(jLabel7)
                            .addComponent(jLabel14))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulocaso, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addComponent(txtIdCaso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarIdcaso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(11, 11, 11))
                                .addComponent(cboOcupacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(cboTestigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboOcupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarIdcaso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitulocaso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelGeneral.addTab("Registrar", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGeneral)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        panelGeneral.setEnabledAt(1, true);
        panelGeneral.setEnabledAt(0, false);
        panelGeneral.setSelectedIndex(1);
        this.accion = "guardar";
        btnGuardar.setText("Guardar");
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        try {
            String respuesta, correo;
            correo = txtCorreo.getText();
            String anonimo = cboTestigo.getSelectedItem().toString();
            if (anonimo.equalsIgnoreCase("Testigo anonimo") || anonimo.equalsIgnoreCase("Testigo Anónimo") || anonimo.equalsIgnoreCase("anonimo") || anonimo.equalsIgnoreCase("Testigo Confidencial") || anonimo.equalsIgnoreCase("confidencial") || anonimo.equalsIgnoreCase("Testigo secreto") || anonimo.equalsIgnoreCase("secreto")) {
                //--------TESTIGO ANONIMO---------//
                JOptionPane.showMessageDialog(this, "Entrando");
                if (this.accion.equals("editar")) {
                    Object itemEstadoCivil = cboEstadoCivil.getSelectedItem();
                    int estadoC = ((EstadoCivil) itemEstadoCivil).getId();
                    Object itemOcupacion = cboOcupacion.getSelectedItem();
                    int ocupacion = ((Ocupacion) itemOcupacion).getId();
                    Object itemTpTestigo = cboTestigo.getSelectedItem();
                    int testigo = ((TipoTestigo) itemTpTestigo).getId();

                    objeto.setId(Integer.parseInt(txtId.getText()));
                    objeto.setNombre(txtNombre.getText());
                    objeto.setApellido(txtApellido.getText());
                    objeto.setIdentidad(txtIdentidad.getText());
                    objeto.setTelefono(txtTelefono.getText());
                    objeto.setCorreo(txtCorreo.getText());
                    objeto.setDomicilio(txtDomicilio.getText());
//              objeto.setFechaNacimiento(fechaSQL);
                    objeto.setIdEstadoCivil(estadoC);
                    objeto.setIdOcupacion(ocupacion);
                    objeto.setIdTipoTestigo(testigo);
                    objeto.setIdCaso(Integer.parseInt(txtIdCaso.getText()));
                    respuesta = CONTROL.actualizar(objeto);
                    if (respuesta.equals("OK")) {
                        this.mensajeOk("Actualizado Correctamente");
                        this.limpiar();
                        this.listar("");
                        panelGeneral.setSelectedIndex(0);
                        panelGeneral.setEnabledAt(1, false);
                        panelGeneral.setEnabledAt(0, true);
                    } else {
                        this.mensajeError(respuesta);
                    }
                } else {
                    //GUARDAR
                    //JOptionPane.showMessageDialog(this, "Entrando A INSERTAR TESTIGO ANONIMO");
//                Object itemEstadoCivil = cboEstadoCivil.getSelectedItem();
//                int estadoC = ((EstadoCivil) itemEstadoCivil).getId();
//                Object itemOcupacion = cboOcupacion.getSelectedItem();
//                int ocupacion = ((Ocupacion) itemOcupacion).getId();
                    Object itemTpTestigo = cboTestigo.getSelectedItem();
                    int testigo = ((TipoTestigo) itemTpTestigo).getId();

                    objeto.setNombre(null);
//                objeto.setApellido(null);
//                objeto.setIdentidad(null);
//                objeto.setTelefono(null);
//                objeto.setCorreo(null);
//                objeto.setDomicilio(null);
//              objeto.setFechaNacimiento(null);
//                objeto.setIdEstadoCivil(null);
//                objeto.setIdOcupacion(null);
                    objeto.setIdTipoTestigo(testigo);
                    objeto.setIdCaso(Integer.parseInt(txtIdCaso.getText()));
                    //JOptionPane.showMessageDialog(this, "Entrando A INSERTAR TESTIGO PASO ADELANTE");
                    respuesta = CONTROL.Insertar(objeto);
                    if (respuesta.equals("OK")) {
                        this.mensajeOk("Guardado Exitosamente");
                        this.limpiar();
                        this.listar("");
                    } else {
                        this.mensajeError(respuesta);
                    }
                }
            } else {
                //--------TESTIGO NORMAL---------//
                //--------VALIDACIONES---------//
                if (txtNombre.getText().length() == 0 || txtNombre.getText().length() > 30) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un nombre y no debe superar los 30 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtNombre.requestFocus();
                    return;
                }
                if (txtApellido.getText().length() == 0 || txtApellido.getText().length() > 30) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar apellidos y no deben superar los 30 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtApellido.requestFocus();
                    return;
                }
                if (txtIdentidad.getText().length() == 0 || txtIdentidad.getText().length() > 17) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un numero de identidad y no debe superar los 17 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtIdentidad.requestFocus();
                    return;
                }
                if (txtTelefono.getText().length() == 0 || txtTelefono.getText().length() > 17) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un numero de telefono y no debe superar los 30 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtTelefono.requestFocus();
                    return;
                }
                if (!correo.matches(EMAIL_PATTERN) || txtCorreo.getText().length() > 150) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un correo valido y no debe superar los 150 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtCorreo.requestFocus();
                    return;
                }
                if (txtDomicilio.getText().length() == 0 || txtDomicilio.getText().length() > 250) {
                    JOptionPane.showMessageDialog(this, "Debes ingresar un domicilio y no debe superar los 250 caracteres", "Bufete", JOptionPane.WARNING_MESSAGE);
                    txtDomicilio.requestFocus();
                    return;
                }
                if (txtFecha.getDate() == null) {
                    JOptionPane.showMessageDialog(this, "debes ingresar una fecha es obligatorio");
                    txtFecha.requestFocus();
                    return;
                }

                if (this.accion.equals("editar")) {
                    java.util.Date fecha = txtFecha.getDate();
                    java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime());

                    Object itemEstadoCivil = cboEstadoCivil.getSelectedItem();
                    int estadoC = ((EstadoCivil) itemEstadoCivil).getId();
                    Object itemOcupacion = cboOcupacion.getSelectedItem();
                    int ocupacion = ((Ocupacion) itemOcupacion).getId();
                    Object itemTpTestigo = cboTestigo.getSelectedItem();
                    int testigo = ((TipoTestigo) itemTpTestigo).getId();

                    objeto.setId(Integer.parseInt(txtId.getText()));
                    objeto.setNombre(txtNombre.getText());
                    objeto.setApellido(txtApellido.getText());
                    objeto.setIdentidad(txtIdentidad.getText());
                    objeto.setTelefono(txtTelefono.getText());
                    objeto.setCorreo(txtCorreo.getText());
                    objeto.setDomicilio(txtDomicilio.getText());
                    objeto.setFechaNacimiento(fechaSQL);
                    objeto.setIdEstadoCivil(estadoC);
                    objeto.setIdOcupacion(ocupacion);
                    objeto.setIdTipoTestigo(testigo);
                    objeto.setIdCaso(Integer.parseInt(txtIdCaso.getText()));
                    respuesta = CONTROL.actualizar(objeto);
                    if (respuesta.equals("OK")) {
                        this.mensajeOk("Actualizado Correctamente");
                        this.limpiar();
                        this.listar("");
                        panelGeneral.setSelectedIndex(0);
                        panelGeneral.setEnabledAt(1, false);
                        panelGeneral.setEnabledAt(0, true);
                    } else {
                        this.mensajeError(respuesta+"dsfsfsdfds");
                    }
                } else {
                    //GUARDAR
                    java.util.Date fecha = txtFecha.getDate();
                    java.sql.Date fechaSQL = new java.sql.Date(fecha.getTime());

                    Object itemEstadoCivil = cboEstadoCivil.getSelectedItem();
                    int estadoC = ((EstadoCivil) itemEstadoCivil).getId();
                    Object itemOcupacion = cboOcupacion.getSelectedItem();
                    int ocupacion = ((Ocupacion) itemOcupacion).getId();
                    Object itemTpTestigo = cboTestigo.getSelectedItem();
                    int testigo = ((TipoTestigo) itemTpTestigo).getId();

                    objeto.setNombre(txtNombre.getText());
                    objeto.setApellido(txtApellido.getText());
                    objeto.setIdentidad(txtIdentidad.getText());
                    objeto.setTelefono(txtTelefono.getText());
                    objeto.setCorreo(txtCorreo.getText());
                    objeto.setDomicilio(txtDomicilio.getText());
                    objeto.setFechaNacimiento(fechaSQL);
                    objeto.setIdEstadoCivil(estadoC);
                    objeto.setIdOcupacion(ocupacion);
                    objeto.setIdTipoTestigo(testigo);
                    objeto.setIdCaso(Integer.parseInt(txtIdCaso.getText()));
                    respuesta = CONTROL.Insertar(objeto);
                    if (respuesta.equals("OK")) {
                        this.mensajeOk("registrado exitosamente");
                        this.limpiar();
                        this.listar("");

                    } else {
                        this.mensajeError(respuesta);
                    }
                }
            }
        } catch (Exception e) {
            this.mensajeOk(e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        panelGeneral.setEnabledAt(1, false);
        panelGeneral.setEnabledAt(0, true);
        panelGeneral.setSelectedIndex(0);
        this.limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
        if (tablaListado.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 3));

            if (JOptionPane.showConfirmDialog(this, "¿Quieres activar el registro: " + nombre + " ?", "Activar", JOptionPane.YES_NO_OPTION) == 0) {
                String respuesta = this.CONTROL.activar(Integer.parseInt(id));
                if (respuesta.equals("OK")) {
                    this.mensajeOk("Registro activado");
                    this.listar("");
                } else {
                    this.mensajeError(respuesta);
                }
            }
        } else {
            this.mensajeError("Seleccione 1 registro a activar.");
        }
    }//GEN-LAST:event_btnActivarActionPerformed

    private void btnDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesactivarActionPerformed
        // TODO add your handling code here:
        if (tablaListado.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 3));

            if (JOptionPane.showConfirmDialog(this, "Deseas desactivar el registro: " + nombre + " ?", "Desactivar", JOptionPane.YES_NO_OPTION) == 0) {
                String respuesta = this.CONTROL.desactivar(Integer.parseInt(id));
                if (respuesta.equals("OK")) {
                    this.mensajeOk("Registro desactivado");
                    this.listar("");
                } else {
                    this.mensajeError(respuesta);
                }
            }
        } else {
            this.mensajeError("Seleccione 1 registro a desactivar.");
        }
    }//GEN-LAST:event_btnDesactivarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:

        if (tablaListado.getSelectedRowCount() == 1) {
            String id = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 0));
            String nombre = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 1));
            String apellido = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 2));
            String identidad = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 3));
            String telefono = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 4));
            String nombreEstadoCivil = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 5));
            String idCaso = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 6));
//            String tituloCaso = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 7));
            String nombreOcupacion = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 8));
            String obteniendoTestigo = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 9));
            String correo = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 10));
            String domicilio = String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 11));
            String fechaNacimiento = tablaListado.getValueAt(tablaListado.getSelectedRow(), 12).toString();
            int idEstadoCivil = Integer.parseInt(String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 13)));
            int idOcupacion = Integer.parseInt(String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 14)));
            int idTpTestigo = Integer.parseInt(String.valueOf(tablaListado.getValueAt(tablaListado.getSelectedRow(), 15)));

            if (obteniendoTestigo.equalsIgnoreCase("Testigo anonimo") || obteniendoTestigo.equalsIgnoreCase("Testigo Anónimo") || obteniendoTestigo.equalsIgnoreCase("anonimo") || obteniendoTestigo.equalsIgnoreCase("Testigo Confidencial") || obteniendoTestigo.equalsIgnoreCase("confidencial")) {
                EstadoCivil itemEstadoCivil = new EstadoCivil(idEstadoCivil, nombreEstadoCivil);
                cboEstadoCivil.setSelectedItem(itemEstadoCivil);
                Ocupacion itemOcupacion = new Ocupacion(idOcupacion, nombreOcupacion);
                cboOcupacion.setSelectedItem(itemOcupacion);
                TipoTestigo itemTipoTestigo = new TipoTestigo(idTpTestigo, obteniendoTestigo);
                cboTestigo.setSelectedItem(itemTipoTestigo);

                this.accion = "editar";
                btnGuardar.setText("Editar");
                panelGeneral.setEnabledAt(0, false);
                panelGeneral.setEnabledAt(1, true);
                panelGeneral.setSelectedIndex(1);
            } else {
                this.accion = "editar";
                btnGuardar.setText("Editar");
                txtId.setText(id);
                txtNombre.setText(nombre);
                txtApellido.setText(apellido);
                txtIdentidad.setText(identidad);
                txtTelefono.setText(telefono);
                txtCorreo.setText(correo);
                txtDomicilio.setText(domicilio);
                txtIdCaso.setText(idCaso);
                this.llenarTextField(Integer.parseInt(idCaso));
                SimpleDateFormat formatoDelTexto = new SimpleDateFormat("yyyy-MM-dd");
                java.util.Date fechaN = null;
                try {
                    fechaN = formatoDelTexto.parse(fechaNacimiento);
                    txtFecha.setDate(fechaN);
                } catch (Exception e) {
                    e.printStackTrace();
                }

                panelGeneral.setEnabledAt(0, false);
                panelGeneral.setEnabledAt(1, true);
                panelGeneral.setSelectedIndex(1);
            }
        } else {
            this.mensajeError("Seleccione 1 registro para editar.");
        }

    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        this.listar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnBuscarIdcasoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdcasoActionPerformed
        // TODO add your handling code here:
        this.llenarTextField(Integer.parseInt(txtIdCaso.getText()));
    }//GEN-LAST:event_btnBuscarIdcasoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarIdcaso;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnDesactivar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cboEstadoCivil;
    private javax.swing.JComboBox<String> cboOcupacion;
    private javax.swing.JComboBox<String> cboTestigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblTitulocaso;
    private javax.swing.JTabbedPane panelGeneral;
    private javax.swing.JTable tablaListado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextArea txtDomicilio;
    private com.toedter.calendar.JDateChooser txtFecha;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdCaso;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
